/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.github.oisaac.exploradordearchivos.vistas.visualizadores;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Isaac
 */
public class VisualizadorImagenes extends javax.swing.JPanel {
    private Image image;
    private File file;
    
    /**
     * Creates new form VisualizadorImagenes
     */
    public VisualizadorImagenes() {
        initComponents();
    }

    public void setFile(File file) {
        this.file = file;
    }
    
    public void setImage(File file) {
        this.image = new ImageIcon(file.getAbsolutePath()).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if (image != null) {
            titulo.setText(file.getName());

            // Gracias chatgpt por pensar esto
            int panelWidth = getWidth();
            int panelHeight = getHeight();
            int imgWidth = image.getWidth(this);
            int imgHeight = image.getHeight(this);

            // Calcular escala manteniendo la relación de aspecto
            double scaleX = (double) panelWidth / imgWidth;
            double scaleY = (double) panelHeight / imgHeight;
            double scale = Math.min(scaleX, scaleY); // Escala uniforme para evitar deformación

            int newWidth = (int) (imgWidth * scale);
            int newHeight = (int) (imgHeight * scale);

            // Centrar la imagen en el panel
            int x = (panelWidth - newWidth) / 2;
            int y = (panelHeight - newHeight) / 2;

            g.drawImage(image, x, y, newWidth, newHeight, this);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        titulo = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        titulo.setText(" ");
        jToolBar1.add(titulo);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
