/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.github.oisaac.exploradordearchivos.vistas.visualizadores;

import io.github.oisaac.exploradordearchivos.logica.JGuiController;
import io.github.oisaac.exploradordearchivos.logica.JIOController;
import io.github.oisaac.exploradordearchivos.logica.JTreeDirectoryController;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Isaac
 */
public class VisualizadorTexto extends javax.swing.JPanel {
    private JIOController jioc = new JIOController(null);
    private JGuiController jgc = new JGuiController(this);
    private JTreeDirectoryController jtdc;
    
    /**
     * Creates new form VisualizadorTexto
     */
    public VisualizadorTexto() {
        initComponents();
    }

    public void setFile(File file) {
        jioc.setFile(file);
    }
    
    public void setTree(JTreeDirectoryController jtdc) {
        this.jtdc = jtdc;
    }
    
    public void renderFile() {
        try {
            title.setText(jioc.getFile().getName());
            contenido.setText(jioc.read());
        } catch (IOException ex) {
            Logger.getLogger(VisualizadorTexto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        contenido = new javax.swing.JTextArea();
        toolbar = new javax.swing.JToolBar();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        guardar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        contenido.setColumns(20);
        contenido.setRows(5);
        scroll.setViewportView(contenido);

        add(scroll, java.awt.BorderLayout.CENTER);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setRollover(true);

        title.setText(" ");
        toolbar.add(title);
        toolbar.add(jSeparator1);

        guardar.setText("Guardar");
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        toolbar.add(guardar);

        add(toolbar, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        File file = jgc.saveFile();
        
        if (file != null) {
            File currentFile = jioc.getFile();
            String textContent = contenido.getText();
            
            if (currentFile.equals(file)) {
                boolean replace = jgc.prompt("Aviso", "¿Quiere remplazar el contenido?");
                if (!replace) return;
            }
            
            try {
                jioc.write(textContent, file, false);
                jgc.alert("Exito", "Archivo guardado con exito");
                contenido.setText(null);
                jtdc.updateTree();
                // Actualiza la rama
            } catch (IOException ex) {
                jgc.alert("Error", ex.getMessage());
            }
        }
    }//GEN-LAST:event_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contenido;
    private javax.swing.JButton guardar;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel title;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
