/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package io.github.oisaac.exploradordearchivos.vistas;

import io.github.oisaac.exploradordearchivos.logica.JTreeDirectoryController;
import io.github.oisaac.exploradordearchivos.logica.JTreeDirectoryNodeController;
import io.github.oisaac.exploradordearchivos.vistas.visualizadores.VisualizadorImagenes;
import io.github.oisaac.exploradordearchivos.vistas.visualizadores.VisualizadorTexto;
import java.io.File;
import java.util.function.Consumer;
import javax.swing.JSplitPane;

/**
 *
 * @author Isaac
 */
public class Explorador extends javax.swing.JInternalFrame {
    private VisualizadorTexto vt = new VisualizadorTexto();
    private VisualizadorImagenes vi = new VisualizadorImagenes();
    
    private File rootFile;

    /**
     * Crear un explorador
     * @param rootFile 
     */
    public Explorador(File rootFile) {
        this.rootFile = rootFile;
        initComponents();
    }
    
    private void onClickListener() {
        // Necesario para acceder la propiedades de mi clase ya que 
        // no puedo hacer un workaround para evitar el caso de JTree del diseñador
        var jtdc = (JTreeDirectoryController) directories;
        
        jtdc.onClick(new Consumer<JTreeDirectoryNodeController>() {
            @Override
            public void accept(JTreeDirectoryNodeController jtdnc) {
                File file = jtdnc.getFile();
                
                if (file.isDirectory()) {
                    return;
                }
                
                if (file.getName().endsWith(".jpg") || file.getName().endsWith(".png")) {
                    vi.setImage(file);
                    vi.setFile(file);
                    layout.add(vi, JSplitPane.RIGHT);
                }
                
                if (file.getName().endsWith(".txt") || file.getName().endsWith(".html"))  {
                    layout.add(vt, JSplitPane.RIGHT);
                    vt.setFile(file);
                    vt.renderFile();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layout = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        directories = new JTreeDirectoryController(rootFile);
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Explorador");

        layout.setDividerLocation(125);
        layout.setResizeWeight(0.5);

        this.onClickListener(); // Esto inicializa los listener
        vt.setTree((JTreeDirectoryController) directories); // Diseñador no hace casting
        jScrollPane1.setViewportView(directories);

        layout.setLeftComponent(jScrollPane1);
        layout.setRightComponent(jPanel1);

        getContentPane().add(layout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree directories;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane layout;
    // End of variables declaration//GEN-END:variables
}
