/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.oisaac.dgt.radar.parser;

import io.github.oisaac.dgt.radar.parser.modelos.Datos;
import io.github.oisaac.dgt.radar.parser.modelos.Infracion;
import io.github.oisaac.dgt.radar.parser.utilidades.UtilidadesColecciones;
import io.github.oisaac.dgt.radar.parser.utilidades.UtilidadesInterfaz;
import io.github.oisaac.dgt.radar.parser.utilidades.UtilidadesString;
import java.util.ArrayList;
import java.util.stream.Collectors;

import static io.github.oisaac.dgt.radar.parser.utilidades.UtilidadesColecciones.row;
import io.github.oisaac.dgt.radar.parser.utilidades.UtilidadesSerializacion;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 *
 * @author Isaac
 */
public class Main extends javax.swing.JFrame {
    private final UtilidadesInterfaz ui = new UtilidadesInterfaz(this);
    private final Datos datos = new Datos();
    
    private ArrayList<String> lineas;
    private ArrayList<Infracion> infraciones;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initOptions();
    }
    
    private void initOptions() {
        this.setLocationRelativeTo(null);
        this.infraciones = datos.getInfraciones();
        this.lineas = datos.getLineas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButtonLeerInfraciones = new javax.swing.JButton();
        jButtonConsultarArchivo = new javax.swing.JButton();
        JButtonConsultarInfraciones = new javax.swing.JButton();
        jButtonLeerArchivo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jLabelLines = new javax.swing.JLabel();
        jLabelInfraciones = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de multas");

        jButtonLeerInfraciones.setText("Leer Infraciones");
        jButtonLeerInfraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeerInfracionesActionPerformed(evt);
            }
        });

        jButtonConsultarArchivo.setText("Consultar Archivo");
        jButtonConsultarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarArchivoActionPerformed(evt);
            }
        });

        JButtonConsultarInfraciones.setText("Consultar Infraciones");
        JButtonConsultarInfraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonConsultarInfracionesActionPerformed(evt);
            }
        });

        jButtonLeerArchivo.setText("Cargar Archivo");
        jButtonLeerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeerArchivoActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar Datos");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCargar.setText("Cargar Datos");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jLabelLines.setText("Posibles Multas: 0");

        jLabelInfraciones.setText("Multas: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLeerArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JButtonConsultarInfraciones)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLeerInfraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelInfraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConsultarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JButtonConsultarInfraciones, jButtonConsultarArchivo, jButtonLeerArchivo, jButtonLeerInfraciones});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCargar, jLabelLines});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLeerArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLeerInfraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelInfraciones)))
                .addGap(18, 18, 18)
                .addComponent(JButtonConsultarInfraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonConsultarInfracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonConsultarInfracionesActionPerformed
        if (infraciones.isEmpty()) {
            ui.alert(
                "Consultar Infraciones", 
                "Los datos de las infraciones no han sido cargadas.", 
                UtilidadesInterfaz.MESSAGE_TYPE.AVISO
            );
        } else {
            String[] columnas = { "Matricula", "Velocidad", "Velocidad Maxima", "Multa", "Fecha" };
            Object[][] filas = UtilidadesColecciones.toRow(infraciones, infracion -> row(
                infracion.matricula(),
                infracion.velocidad(),
                infracion.velocidadMaxima(),
                infracion.multa(),
                infracion.fecha().format(Infracion.FORMATO_FECHA_HORA)
            ));
            
            ui.mostrarTabla("Infraciones", columnas, filas);
        }
    }//GEN-LAST:event_JButtonConsultarInfracionesActionPerformed

    private void jButtonLeerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeerArchivoActionPerformed
        ArrayList<String> contenido = ui.openAndReadFile();
        
        if (contenido.isEmpty()) {
            ui.alert(
                "Leer Archivo", 
                "Archivo no selecionado.", 
                UtilidadesInterfaz.MESSAGE_TYPE.AVISO
            );
        } else {
            this.lineas.clear();
            this.lineas.addAll(contenido);
            
            jLabelLines.setText("Posible Multas: " + this.lineas.size());
            
            ui.alert(
                "Leer Archivo", 
                "Archivo cargado con exito", 
                UtilidadesInterfaz.MESSAGE_TYPE.INFORMACION
            );
        }
    }//GEN-LAST:event_jButtonLeerArchivoActionPerformed

    private void jButtonConsultarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarArchivoActionPerformed
        if (lineas.isEmpty()) {
            ui.alert(
                "Consultar Archivo", 
                "No se han cargado el archivo de infraciones.txt", 
                UtilidadesInterfaz.MESSAGE_TYPE.AVISO
            );
        } else {
            String[] columnas = { "Lineas" };
            Object[][] filas = UtilidadesColecciones.toRow(lineas, linea -> row(linea));
            
            ui.mostrarTabla("Lineas de infraciones", columnas, filas);
        }
    }//GEN-LAST:event_jButtonConsultarArchivoActionPerformed

    private void jButtonLeerInfracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeerInfracionesActionPerformed
        if (lineas.isEmpty()) {
            ui.alert(
                "Leer Infraciones", 
                "No se han cargado el archivo de infraciones.txt", 
                UtilidadesInterfaz.MESSAGE_TYPE.AVISO
            );
        } else {
            // Obtenemos las infraciones sobre las lineas de texto
            ArrayList<Infracion> infracionesLista = lineas.stream()
                .map(UtilidadesString::getInfracionFromLine)
                .filter(Infracion::esMatriculaValida)
                .collect(Collectors.toCollection(ArrayList::new));
            
            // Borramos las antiguas que tengamos y cargamos las nuevas
            this.infraciones.clear();
            this.infraciones.addAll(infracionesLista);
            
            // Modificamos el label
            jLabelInfraciones.setText("Multas: " + this.infraciones.size());
            
            ui.alert(
                "Leer Infraciones", 
                "Las infraciones ha sido arregladas y cargadas en el sistema.", 
                UtilidadesInterfaz.MESSAGE_TYPE.INFORMACION
            );
        }
    }//GEN-LAST:event_jButtonLeerInfracionesActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        File file = ui.saveFile();
        
        if (file == null) {
            ui.alert(
                "Guardar Datos", 
                "No has selecionado donde lo vas ha guardar", 
                UtilidadesInterfaz.MESSAGE_TYPE.AVISO
            );
        } else {
            if (file.exists()) {
                boolean replace = ui.prompt("Guardar datos", "Seguro que quiere remplazar el archivo?");
            
                if (!replace) 
                    return;
            }
            
            try {
                UtilidadesSerializacion.save(datos, file);
                ui.alert(
                    "Guardar Datos", 
                    "Datos guardados con exito!", 
                    UtilidadesInterfaz.MESSAGE_TYPE.INFORMACION
                );
            } catch (IOException ex) {
                ui.alert(
                    "Guardar Datos", 
                    "Error al guardar: " + ex.getMessage(), 
                    UtilidadesInterfaz.MESSAGE_TYPE.ERROR
                );
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
       File file = ui.openFile();
       
       if (file == null) {
           ui.alert(
                "Cargar Datos", 
                "No has selecionado archivo para cargar", 
                UtilidadesInterfaz.MESSAGE_TYPE.AVISO
            );
       } else {
           try {
                Datos datosCargados = UtilidadesSerializacion.open(file, Datos.class);
                
                this.infraciones = datosCargados.getInfraciones();
                this.lineas = datosCargados.getLineas();
                
                jLabelInfraciones.setText("Multas: " + this.infraciones.size());
                jLabelLines.setText("Posible Multas: " + this.lineas.size());

                ui.alert(
                    "Cargar Datos", 
                    "Datos cargados con exito!", 
                    UtilidadesInterfaz.MESSAGE_TYPE.INFORMACION
                );
            } catch (IOException | ClassNotFoundException ex) {
                ui.alert(
                    "Guardar Datos", 
                    "Error al guardar: " + ex.getMessage(), 
                    UtilidadesInterfaz.MESSAGE_TYPE.ERROR
                );
            }
       }
    }//GEN-LAST:event_jButtonCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonConsultarInfraciones;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonConsultarArchivo;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLeerArchivo;
    private javax.swing.JButton jButtonLeerInfraciones;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabelInfraciones;
    private javax.swing.JLabel jLabelLines;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
